name: Run tests

on: [push, pull_request]

jobs:
  test:
    name: ${{ matrix.os }} - ${{ matrix.version }} - $${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: '1' 
            os: ubuntu-latest
            arch: x64
          - version: '1'  
            os: windows-latest
            arch: x64
          - version: '1'
            os: macOS-latest
            arch: x64
          - version: '1.6'  
            os: ubuntu-latest
            arch: x64
          - version: '1.6'  
            os: ubuntu-latest
            arch: x86
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info